baseURL       = "https://milad.dev"
languageCode  = "en-us"
title         = "Milad Irannejad"
theme         = "hermit"
enableGitInfo = true
# enableEmoji = true

# Taxonomies
[taxonomies]
  tag      = "tags"
  category = "categories"

# Code Highlighting
# pygmentsUseClassic = true
# pygmentsCodefences = true

# Enable Google Analytics
googleAnalytics = "UA-141297099-1"

[author]
  name = "Milad Irannejad"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  justifyContent = true
  homeSubtitle   = "Writing about tech and dev"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/moorara/milad.dev/commit/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/moorara"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/moorara"

[menu]

  [[menu.main]]
    name   = "Posts"
    url    = "posts/"
    weight = 10

  [[menu.main]]
    name   = "Gists"
    url    = "gists/"
    weight = 20

  [[menu.main]]
    name   = "Projects"
    url    = "projects/"
    weight = 30

  [[menu.main]]
    name   = "Fav Books"
    url    = "books/"
    weight = 40

  [[menu.main]]
    name   = "Fav Reads"
    url    = "reads"
    weight = 50

  [[menu.main]]
    name   = "Fav Quotes"
    url    = "quotes"
    weight = 60

  [[menu.main]]
    name   = "About Me"
    url    = "about"
    weight = 70
